apiVersion: v1
kind: ConfigMap
metadata:
  name: erapport-config
  namespace: erapport
data:
  PORT: "3001"
  TRUST_PROXY: "true"
  SERVER_BASE_URL: "https://erapport.app.emfnet.ch"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: erapport
data:
  MARIADB_DATABASE: erapport
  MARIADB_USER: erapport
